steps:
  - label: ":bazel: Build and test libraries and services"
    key: "build-and-test"
    command: |
      echo "--- :books: Building libraries"
      bazel build //lib/...

      echo "--- :test_tube: Testing libraries"
      bazel test //lib/...

      echo "--- :package: Building services"
      bazel build //services/...

      echo "--- :test_tube: Testing services"
      bazel test //services/...

      echo "--- :bar_chart: Gathering Bazel stats"
      bazel info 2>&1 | tee bazel-info.txt || true

      echo "--- :arrow_up: Uploading service binaries"
      buildkite-agent artifact upload "bazel-bin/services/auth/auth_/auth"
      buildkite-agent artifact upload "bazel-bin/services/payment/payment_/payment"
      buildkite-agent artifact upload "bazel-bin/services/user/user_/user"

      echo "--- :memo: Creating build annotation"
      cat << EOF | buildkite-agent annotate --style info --context bazel-stats
      ## :bar_chart: Bazel Build Statistics

      **Build Summary:**
      - :white_check_mark: All libraries built successfully
      - :white_check_mark: All library tests passed
      - :white_check_mark: All services built successfully
      - :white_check_mark: All service tests passed

      **Artifacts uploaded:**
      - \`services/auth/auth\`
      - \`services/payment/payment\`
      - \`services/user/user\`

      **Bazel Info:**
      \`\`\`
      $(cat bazel-info.txt)
      \`\`\`
      EOF
    artifact_paths:
      - "bazel-bin/services/auth/auth_/auth"
      - "bazel-bin/services/payment/payment_/payment"
      - "bazel-bin/services/user/user_/user"
