steps:
  - label: ":bazel: :test_tube: Build and test all targets"
    key: "build-and-test"
    command: |
      # Build libraries first
      echo "--- :books: Building libraries"
      bazel build //lib/...

      # Build services
      echo "--- :rocket: Building services"
      bazel build //services/...

      # Run all tests
      echo "--- :test_tube: Running tests"
      bazel test //...

      # Upload service binaries as artifacts
      echo "--- :package: Uploading service artifacts"
      buildkite-agent artifact upload "bazel-bin/services/auth/auth_/auth"
      buildkite-agent artifact upload "bazel-bin/services/payment/payment_/payment"
      buildkite-agent artifact upload "bazel-bin/services/user/user_/user"

      # Generate and upload build statistics annotation
      echo "--- :bar_chart: Generating build statistics"
      cat << 'EOF' | buildkite-agent annotate --style "info" --context "bazel-stats"
      ## :bazel: Bazel Build Statistics

      ### :books: Libraries Built
      - \`//lib/config:config\`
      - \`//lib/logging:logging\`
      - \`//lib/metrics:metrics\`
      - \`//lib/tracing:tracing\`

      ### :rocket: Services Built
      - \`//services/auth:auth\`
      - \`//services/payment:payment\`
      - \`//services/user:user\`

      ### :test_tube: Tests Executed
      All test targets in \`//...\`

      ### :package: Artifacts Uploaded
      - \`auth\` service binary
      - \`payment\` service binary
      - \`user\` service binary
      EOF
