env:
  BAZEL_CONFIG: "ci"

steps:
  - label: ":bazel: Setup and Dependencies"
    command: |
      echo "--- Setting up Bazel environment"
      bazel version
      echo "--- Fetching dependencies"
      bazel fetch //...

  - label: ":building_construction: Build All Targets"
    command: |
      echo "--- Building all targets"
      bazel build //...

  - label: ":test_tube: Run All Tests"
    command: |
      echo "--- Running all tests"
      bazel test //... --test_output=errors

  - label: ":package: Build Service Binaries"
    command: |
      echo "--- Building service binaries"
      bazel build //services/auth:auth
      bazel build //services/user:user
      bazel build //services/payment:payment

  - label: ":mag: Verify Build Artifacts"
    command: |
      echo "--- Verifying build artifacts exist"
      ls -la bazel-bin/services/auth/
      ls -la bazel-bin/services/user/
      ls -la bazel-bin/services/payment/

  - wait

  - label: ":rocket: Package and Archive"
    command: |
      echo "--- Creating release artifacts"
      mkdir -p artifacts
      cp bazel-bin/services/auth/auth_/auth artifacts/auth-service
      cp bazel-bin/services/user/user_/user artifacts/user-service
      cp bazel-bin/services/payment/payment_/payment artifacts/payment-service
      echo "--- Artifacts created:"
      ls -la artifacts/
    artifact_paths:
      - "artifacts/*"

  - label: ":chart_with_upwards_trend: Generate Dependency Graph"
    command: |
      echo "--- Generating dependency graph"
      bazel query --output=graph //... | dot -Tpng -o dependency-graph.png
      echo "--- Graph generated successfully"
    artifact_paths:
      - "dependency-graph.png"
    soft_fail: true  # Graph generation is nice-to-have
