steps:
  - label: ":bazel: Build and test all targets"
    key: "build-and-test"
    command: |
      echo "--- :package: Building libraries"
      bazel build //lib/...

      echo "--- :rocket: Building services"
      bazel build //services/...

      echo "--- :test_tube: Running all tests"
      bazel test //...

      echo "--- :bar_chart: Collecting build stats"
      cat <<EOF | buildkite-agent annotate --style info --context build-stats
      ## :chart_with_upwards_trend: Bazel Build Statistics

      **Libraries Built:**
      - \`//lib/config\` - Configuration management
      - \`//lib/logging\` - Shared logging utilities
      - \`//lib/metrics\` - Metrics collection
      - \`//lib/tracing\` - Environment-specific tracing

      **Services Built:**
      - \`//services/auth\` - Authentication service
      - \`//services/payment\` - Payment processing service
      - \`//services/user\` - User management service

      **Test Results:**
      All tests passed :white_check_mark:
      EOF

      echo "--- :package: Uploading service binaries as artifacts"
      buildkite-agent artifact upload "bazel-bin/services/auth/auth_/auth"
      buildkite-agent artifact upload "bazel-bin/services/payment/payment_/payment"
      buildkite-agent artifact upload "bazel-bin/services/user/user_/user"
